---
version: 0.2
env:
  parameter-store:
    TOKEN: GitHubToken
phases:
  build:
    commands:
      - pip install --upgrade pip
      - pip install awscli --upgrade
      - cd $CODEBUILD_SRC_DIR
      - git config --global credential.*.username $TOKEN
      - git config --global core.askPass "/bin/true"
      - pip install -r imdb-datasets-handler/layer/requirements.pip -t imdb-datasets-handler/layer/python
      - echo $ArtifactBucket
      - echo KMSKey
      - aws cloudformation package --template-file cloud-formation/imdb-datasets-handler/template.yaml --s3-bucket $ArtifactBucket --kms-key-id $KMSKey --output-template-file imdb-datasets-handler.yaml-processed
  post_build:
    commands:
      - echo "Build completed on `date`"
artifacts:
  files:
    - imdb-datasets-handler.yaml-processed