AWSTemplateFormatVersion: 2010-09-09
Transform: "AWS::Serverless-2016-10-31"
Parameters:
  ImdbDatasetFiles:
    Description: List of files to delete, separated by ;
    Type: String
    Default: name.basics.tsv.gz
  ImdbDatasetBaseUrl:
    Description: Base URL for imdb dataset
    Type: String
    Default: https://datasets.imdbws.com/

Resources:
  StorageBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete

  StorageBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StorageBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - s3:*
            Resource:
              - !Sub arn:aws:s3:::${StorageBucket}
              - !Sub arn:aws:s3:::${StorageBucket}/*
            Principal:
              AWS:
                - !Sub arn:aws:iam::${AWS::AccountId}:root

  # Lambdas Role
  LambdasRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'

  IMDBDatasetsHandlerLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../imdb-datasets-handler/lambda
      MemorySize: 512
      Handler: imdb_datasets.lambda_handler
      Role: !GetAtt LambdasRole.Arn
      Timeout: 300
      Layers:
        - !Ref IMDBDatasetsHandlerLayer
      Runtime: python3.7
      FunctionName: imdb-datasets-handler
      Environment:
        Variables:
          STORAGE_BUCKET: !Ref StorageBucket
          IMDB_DATASET_FILES: !Ref ImdbDatasetFiles
          IMDB_DATASET_BASE_URL: !Ref ImdbDatasetBaseUrl

  IMDBDatasetsHandlerLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.7
      ContentUri: ../../imdb-datasets-handler/layer
      Description: "IMDB Datasets layer"
      LayerName: imdb-datasets-handler-layer

  AssumeRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: imdb-datasets-handler-policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          # Log-related access
          - Effect: Allow
            Action:
              - 'logs:CreateLogStream'
              - 'logs:CreateLogGroup'
              - 'logs:PutLogEvents'
            Resource: 
              - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${IMDBDatasetsHandlerLambda}:*"
          # Lambdas-related access
          - Effect: Allow
            Action:
              - 'lambda:InvokeFunction'
              - 'lambda:ListFunctions'
              - 'lambda:AddPermission'
            Resource: "*"
      Roles:
        - !Ref LambdasRole

Outputs:
  IMDBDatasetsHandlerLambdaName:
    Description: Watcher Event Evaluate Policies Lambda Name
    Value: !GetAtt IMDBDatasetsHandlerLambda.Arn
    Export:
      Name: IMDBDatasetsHandlerLambdaName
